### ISSUE TITLE
RPNet-e100.pth missing

### ISSUE THREAD

**Issue by Gagan2002** [zjykzj/LPDet#1]
hi,

i am trying to run the demo, how can i test it?
i cant find the file RPNet-e100.pth

the Baidu link isnt accessible, can you provide google drive link ?

thanks

**Comment by zjykzj** [comment]
> hi,
> 
> i am trying to run the demo, how can i test it? i cant find the file RPNet-e100.pth
> 
> the Baidu link isnt accessible, can you provide google drive link ?
> 
> thanks

See https://github.com/zjykzj/LPDet/releases/tag/v0.3.0
