### ISSUE TITLE
I want trained by green dataset but get error assertion outputs len != 11

### ISSUE THREAD

**Issue by GigaDevelopper** [zjykzj/LPDet#2]

**Comment by zjykzj** [comment]
@GigaDevelopper More infos. Your dataset format? How to start training? And detailed error logs?

**Comment by GigaDevelopper** [comment]
> @GigaDevelopper More infos. Your dataset format? How to start training? And detailed error logs?

I trained with green dataset but get error assertion "outputs[0] len !=11"
I rewrite this assertion in loss.py .
and trained wR2.pth 
But when I use with pre trained wr I get error 
```
(venv) azmiddin@azmiddin-HP-Laptop-15-dy2xxx:~/project-parking/parking-anpr/LPDet$ python3 predict_wr2.py wR2-e100.pth assets/eval/1.jpg
args: Namespace(wr2='wR2-e100.pth', image='assets/eval/1.jpg')
Loading wR2 pretrained: wR2-e100.pth
torch.Size([1, 4])
Traceback (most recent call last):
  File "/home/azmiddin/project-parking/parking-anpr/LPDet/predict_wr2.py", line 65, in <module>
    cv2.rectangle(image, (int(x_min), int(y_min)), (int(x_max), int(y_max)), (0, 0, 255), 2)
                          ^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

**Comment by GigaDevelopper** [comment]
And how I can get confidience ?

**Comment by zjykzj** [comment]
> > @GigaDevelopper More infos. Your dataset format? How to start training? And detailed error logs?
> 
> I trained with green dataset but get error assertion "outputs[0] len !=11" I rewrite this assertion in loss.py . and trained wR2.pth But when I use with pre trained wr I get error
> 
> ```
> (venv) azmiddin@azmiddin-HP-Laptop-15-dy2xxx:~/project-parking/parking-anpr/LPDet$ python3 predict_wr2.py wR2-e100.pth assets/eval/1.jpg
> args: Namespace(wr2='wR2-e100.pth', image='assets/eval/1.jpg')
> Loading wR2 pretrained: wR2-e100.pth
> torch.Size([1, 4])
> Traceback (most recent call last):
>   File "/home/azmiddin/project-parking/parking-anpr/LPDet/predict_wr2.py", line 65, in <module>
>     cv2.rectangle(image, (int(x_min), int(y_min)), (int(x_max), int(y_max)), (0, 0, 255), 2)
>                           ^^^^^^^^^^
> ValueError: cannot convert float NaN to integer
> ```

Again, what's `green dataset` means? Can you provide a detailed description? Give some pictures?

For the error log above, it is obvious that it provides error information: the model failed to predict coordinates. This could be due to your training failure.

**Comment by zjykzj** [comment]
> And how I can get confidience ?

For license plate detection, L1Loss was used without confidence prediction
